require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'db/schema.rb'
    - 'Rakefile'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Metrics/MethodLength:
  Max: 20

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'config/environment.rb'
