services:
  auth-service:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - database
    env_file:
      - .env.test

  database:
    image: postgres:16.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.test

