name: auth-service
services:
  auth-service-migration:
    build: .
    command: >
      /bin/sh -c "bundle exec rake db:create && bundle exec rake db:migrate"
    volumes:
      - .:/app
    depends_on:
      database:
        condition: service_healthy
    environment:
      - APP_ENV

  auth-service:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_started
      database:
        condition: service_healthy
      auth-service-migration:
        condition: service_completed_successfully
    environment:
      - APP_ENV

  auth-service-background:
    build: .
    command: "bundle exec sidekiq -r ./config/sidekiq_config.rb"
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_started
      database:
        condition: service_healthy
      auth-service-migration:
        condition: service_completed_successfully
    environment:
      - APP_ENV

  database:
    image: postgres:16.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=arival
      - POSTGRES_PASSWORD=73d2df53f2df009d
      - POSTGRES_DB=arival_development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER --dbname $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./tmp/redis:/data
