version: '3.4'
services:
  auth-service:
    build: .
    target: production
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - database

  database:
    image: postgres:16.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $ARIVAL_AUTH_DB_USER
      POSTGRES_PASSWORD: $ARIVAL_AUTH_DB_PASSWORD
